# Generated by Django 5.0.6 on 2024-07-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flan",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="flan",
            name="image_url",
            field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="flan",
            name="is_private",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="flan",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
