# Generated by Django 5.0.6 on 2024-07-11 20:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Web", "0002_alter_flan_description_alter_flan_image_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_form_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_name", models.CharField(max_length=64)),
                ("message", models.TextField()),
            ],
        ),
    ]
