# Generated by Django 3.2 on 2024-07-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasteles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flan_uuid', models.UUIDField()),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(default='')),
                ('image_url', models.URLField(default='')),
                ('slug', models.SlugField(default='')),
                ('is_private', models.BooleanField(default=True)),
            ],
        ),
    ]
